version: '3.7' # specify docker-compose version
# Define the services/containers to be run
services:
  frontend: #name of the first service
    build: frontend # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
    container_name: frontend
  backend: #name of the second service
    build: backend # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    container_name: backend
    links:
      - database # link this service to the database service
  database: # name of the third service
    #build: database # to specify the directory of the Dockerfile
    # In production, you may want to use a managed database service
    image: mongo
    container_name: database
    environment:
       - MONGO_INITDB_DATABASE=database
    #    - MONGO_INITDB_ROOT_USERNAME=root
        # You should definitely change the password in production
    #    - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
        #- db-data:/var/lib/mongodb/data:rw
        # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
        - ./docker/db/data:/var/lib/mongodb/data:rw
    ports:
        - "27017:27017"